artifacts_root: artifacts
training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
prepare_base_model:
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
data_ingestion:
  unzip_dir: artifacts/data_ingestion
  training_data: artifacts/data_ingestion/Chest-CT-Scan-data.zip
  training_data_dir: artifacts/data_ingestion/Chest-CT-Scan-data
  training_data_csv: artifacts/data_ingestion/train.csv
